#---------------------------------------------------------------------------
# Copyright IBM Corp. 2015, 2015 All Rights Reserved
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# Limitations under the License.
#---------------------------------------------------------------------------
# Written By George Goldberg (georgeg@il.ibm.com)
---
redhat_packages:
  - openstack-swift-account
  - openstack-swift-container
  - openstack-swift-object
  - xinetd

redhat_services:
  - openstack-swift-object
  - openstack-swift-object-replicator 
  - openstack-swift-object-updater 
  - openstack-swift-object-auditor
  - openstack-swift-container
  - openstack-swift-container-replicator 
  - openstack-swift-container-updater 
  - openstack-swift-container-auditor
  - openstack-swift-account
  - openstack-swift-account-replicator
  - openstack-swift-account-reaper
  - openstack-swift-account-auditor

debian_packages:
  - python-xattr
  - rsync
  - swift
  - swift-account
  - swift-container
  - swift-object
  - python-keystoneclient
  - python-swiftclient

debian_services:
  - swift-account
  - swift-account-auditor
  - swift-account-reaper
  - swift-account-replicator
  - swift-container
  - swift-container-auditor
  - swift-container-replicator
  - swift-container-updater
  - swift-object
  - swift-object-auditor
  - swift-object-replicator
  - swift-object-updater

config_files:
  - swift.conf
  - account-server.conf
  - container-server.conf
  - object-server.conf
