#---------------------------------------------------------------------------
# Copyright IBM Corp. 2015, 2015 All Rights Reserved
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# Limitations under the License.
#---------------------------------------------------------------------------
# Written By George Goldberg (georgeg@il.ibm.com)
---
- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: create directories if not already there
  file:
    path: "{{ item }}"
    owner: "swift"
    group: "swift"
    mode: 0750
    state: directory
  with_items:
    - /etc/swift
    - /srv/node
    - /var/lib/swift
    - /var/cache/swift

- name: update configuration swift files from templates
  template: 
    src: "{{ item.value[openstack_version]  }}"
    dest: /etc/swift/{{ item.key }}
    owner: "swift"
    group: "swift"
    mode: 0600
  with_dict: config_files
  tags:
    - config_files

- name: enable services 
  service: 
    name: "{{ item }}"
    enabled: yes
    state: stopped
  with_items: services
